---
- name: Setup Docker on Debian
  hosts: debian-docker
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install CA Certificates and Curl
      apt:
        name:
          - ca-certificates
          - curl
        state: present
    - name: Create keys directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Store architecture in a variable
      command: "dpkg --print-architecture"
      register: dpkg_print_arch_result
    - name: Add Docker repository to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ dpkg_print_arch_result.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes
    - name: Update apt caches
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Add user to Docker group
      user:
        name: debian
        groups: docker
        append: yes
